language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: o+FeUuqY6gg9UUAEbl7O3GRWB8SWLxEMYWYz33YPxMPREBXNi8tyWdzNADiXDybnLaMpk2aWKrOQRdPxRz5c8XvvUva4qkKGKjpMUBRGHKuB+eFOwxvge8t4DY9h/Q4b0oI1cFm2a9+UV0T/ia8yOHwJ5Y8+CPat/WFLo+uoh65TKLXI5b2e9dqjbft9b03C8rBEDjyTc+UY2i+vUnocdUHMGwKpBvOEBHcpWQHUU2RgT4Z0zhIiuD6pQKwg3yrbWBJn2r5AjfNWC6HtrMptvKWf3bRGjVOEGfUbbBZicwK5CNnL9sN1XYxbrgywpNPM0ynm5vG/eMGs3ucKqfKvsT0kW89ZmokxGRFZxOHWTc/r8oxTyjJSOukmtxA/+qki7CyWSViT2GEUE9BEmW14zSnGUxV0UA4vxRQN7aqUMKeXHSu2ROHnh+lXGsFYwc1DIxyrUzqKIssUryGNPFOuxuVPDQNmGdey+bXAyZ4/Z2MAJkMUzP1lQssgCQ9TWwNfsgALOoGIscl2t63lQxSWWhozTU2Dm426/c8ARW/gpEVoj1EQo88m2qpHziNStTDtOy0fwumvWSUfrsQhfkTb6v/FocLqg2RUwIaeZ4OylEbOmxnBGPgn6xUWOwjCjLWAhKiZBb45NeCecvvHDL+odaxan7WAX+nmjxn916iy7cg=
  app: peaceful-ridge-12452
  on:
    repo: shanescott/DMFlow
